### ISSUE TITLE
parser data (string , file ..)

### ISSUE THREAD

**Issue by ButterflyEffect** [anhero/JsonBox#14]
i use this lib to paser string or file , i found :

void Value::loadFromString(std::string const &json)
 {
		std::stringstream jsonStream(json);
		loadFromStream(jsonStream);
}

return void ,  i can't know parser success or fail ?

can you  add a flag (bool , return trun or false) ?

**Comment by madbranch** [comment]
I have updated the error handling system. An exception should be thrown when an error occurs.
