### ISSUE TITLE
Missing elements in large arrays

### ISSUE THREAD

**Issue by Zylann** [anhero/JsonBox#15]
GO DOWN FOR FIX

I tried to read a JSON map from Tiled. There is an array in it that was supposed to have 5000 elements, but it ended up with 4998.
I checked the number of commas with a text editor and I found 4999 (then 5000 since the last element doesn't have one).

I ran a test with the following JSON file : http://zylannprods.fr/dl/big_array.json
With the following code :
 JsonBox::Value v;
 v.loadFromFile("big_array.json");
 cout << v["data"].getArray().size() << endl;

The array had 324 elements, fine. Then, I added a ", 0" at the end of the array.
I re-ran the test. It found 324 elements too. If I add another element in the file, it goes to 325, 326 etc, but one is missing.

Finally, something weirder : I tried to add digits to numbers in the array, making the file bigger in size without actually adding elements, and I noticed the same impact on missing elements.

I think the issue is not directly related to parsing, maybe it has to do with buffers flushing?

I'm on Windows 7 64 bits, my compiler is MinGW32-GCC TDM (the one bundled with Code::Blocks 12.11).

EDIT: It happens with string arrays too, more likely if they have various sizes.
EDIT2: Ok, I tried with an array containing 5700 "b", it found 5668.
EDIT3: I tried to output the parsed data as JSON : values in the array are PERIODICALLY wrong (every 288 with a series of 5700 "b", that get replaced by "" or "\t").

EDIT4: Oh ! There is no specifications about the opening mode in loadFromFile()... I get my 5700 "b" if I add std::ios::binary|std::ios::in as second parameter of stream opening :D Adding "âéèbb" seem to work in this mode too.

**Comment by madbranch** [comment]
Thank you very much for doing all that research!
