### ISSUE TITLE
[]  and = operator  always new memory?  setInt setString  will save much memory?

### ISSUE THREAD

**Issue by cnsoft** [anhero/JsonBox#21]
e.g:    
val["positionx"] = 10; 
val["positionx"].setInt(10);

is there some different with the two different function call?

**Comment by madbranch** [comment]
The operator= for the class Value has only been defined as
```cpp
Value &operator=(const Value &src);
```
So when you write:
```cpp
val["positionx"] = 10;
```
A Value instance is implicitly created using the following constructor:
```cpp
Value(int newInt);
```
So in your example, the call to setInt(10) is probably much faster than using the operator=
