### ISSUE TITLE
Get JSON result in one line

### ISSUE THREAD

**Issue by stepanov** [anhero/JsonBox#27]
Hi,
Is it possible to generate JSON result in one line without any \t, \n, \r ?

**Comment by ben-crowhurst** [comment]
Please take the time to explore the codebase/documentation before distracting developers.

   Value json
   json.writeToStream( stream, styled );

Styled = Boolean data-type.

**Comment by stepanov** [comment]
Hi, thank you for clarification and sorry for distraction. But more examples will help to avoid such distractions.
