### ISSUE TITLE
Explain how to check if object contains an attribute in docs

### ISSUE THREAD

**Issue by mbabuskov** [anhero/JsonBox#29]
It took me some time to find this and I'm still not sure if it was the proper way. 
```
if (object.find("property") != object.end())
```
It would be even better if getXXX() methods could supply a default value. For example, I want to distinguish when some integer value is zero, vs when it is not present in JSON file at all. 

Example:
```
int x = o["something"].getInteger(10);
```
would mean: get the value and if it does not exist, return 10.

**Comment by madbranch** [comment]
This not a bad idea. I'll work on it.

**Comment by madbranch** [comment]
I wrote some methods that are used like this :
```
int x = o["something"].tryGetInteger(10);
double y = o["something"].tryGetDouble(12.0);
float z = o["something"].tryGetFloat(13.0f);
bool b = o["something"].tryGetBoolean(true);
std::string s = o["something"].tryGetString("madbranch");
```

**Comment by mbabuskov** [comment]
Excellent! Thanks a lot. :)
