### ISSUE TITLE
OutputFilter::setbuf does not overload

### ISSUE THREAD

**Issue by mwoehlke-kitware** [anhero/JsonBox#30]
The current implementation of `OutputFilter` triggers a `-Woverloaded-virtual` warning because its `setbuf` method hides `std::streambuf::setbuf`:

    /usr/include/c++/4.8.3/streambuf:591:7: error: ‘std::basic_streambuf<_CharT, _Traits>* std::basic_streambuf<_CharT, _Traits>::setbuf(std::basic_streambuf<_CharT, _Traits>::char_type*, std::streamsize) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_streambuf<_CharT, _Traits>::char_type = char; std::streamsize = long int]’ was hidden [-Werror=overloaded-virtual]
           setbuf(char_type*, streamsize)
           ^
    In file included from jsonbox/src/Array.cpp:5:0:
    jsonbox/include/JsonBox/OutputFilter.h:94:27: error:   by ‘std::streambuf* JsonBox::OutputFilter<Inserter>::setbuf(char*, int) [with Inserter = JsonBox::Indenter; std::streambuf = std::basic_streambuf<char>]’ [-Werror=overloaded-virtual]
       virtual std::streambuf *setbuf(char *p, int len) {
                               ^

Considering that `std::streambuf::setbuf` is a virtual method, it would appear that this is intended to be an overload. Unfortunately it is *not* an overload due to a mismatch in parameter types. The second parameter has type `int`, but the correct type for this virtual method is `std::streamsize` (see e.g. http://en.cppreference.com/w/cpp/io/basic_streambuf/pubsetbuf and/or the above compiler diagnostic).

**Comment by madbranch** [comment]
Wow, nice find. I'll take care of it.

**Comment by mwoehlke-kitware** [comment]
Thanks :smile:. (There's a *reason* I pathologically try to build everything with `-Werror=cast-qual -Werror=narrowing -Werror=non-virtual-dtor -Werror=overloaded-virtual -Werror=init-self -Werror=return-type -Werror=ignored-qualifiers`. This is it. You may be pleased to know that this is the only error JsonBox trips with that list.)

If you ever decide you want to make use of C++11, this is why the new `override` keyword exists :grin:.

**Comment by madbranch** [comment]
In the end, the method overrides were empty, so I simply removed them.

**Comment by mwoehlke-kitware** [comment]
Huh... so they were. Thanks!
