### ISSUE TITLE
Missing Export.h

### ISSUE THREAD

**Issue by mbabuskov** [anhero/JsonBox#34]
Compiling the sources fails, because Value.h contains:

#include "Export.h"

But this file is not found.

**Comment by samueldr** [comment]
This file should have been generated from the cmake build process.

Though, I see that if it is not installed, the Export.h is found in the build directory, and not with the include files.

Here's a sample compilation I just did:

    ~/.../jsonbox/test ⃲ git clone git@github.com:anhero/JsonBox.git
    Cloning into 'JsonBox'...
    remote: Counting objects: 1183, done.
    remote: Total 1183 (delta 0), reused 0 (delta 0), pack-reused 1183
    Receiving objects: 100% (1183/1183), 620.78 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (699/699), done.
    Checking connectivity... done.
    
    ~/.../jsonbox/test ⃲ mkdir build
    
    ~/.../jsonbox/test ⃲ cd build/
    
    ~/.../test/build ⃲ cmake ../JsonBox/
    -- The C compiler identification is GNU 5.2.0
    -- The CXX compiler identification is GNU 5.2.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
    -- Configuring done
    CMake Warning (dev) at CMakeLists.txt:36 (add_library):
      Policy CMP0063 is not set: Honor visibility properties for all target
      types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      Target "JsonBox" of type "STATIC_LIBRARY" has the following visibility
      properties set for CXX:
    
        CXX_VISIBILITY_PRESET
        VISIBILITY_INLINES_HIDDEN
    
      For compatibility CMake is not honoring them for this target.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at CMakeLists.txt:82 (add_executable):
      Policy CMP0063 is not set: Honor visibility properties for all target
      types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      Target "example1" of type "EXECUTABLE" has the following visibility
      properties set for CXX:
    
        CXX_VISIBILITY_PRESET
        VISIBILITY_INLINES_HIDDEN
    
      For compatibility CMake is not honoring them for this target.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Generating done
    -- Build files have been written to: /Users/samuel/Projects/jsonbox/test/build
    
    ~/.../test/build ⃲ make
    Scanning dependencies of target JsonBox
    [  9%] Building CXX object CMakeFiles/JsonBox.dir/src/JsonWritingError.cpp.o
    [ 18%] Building CXX object CMakeFiles/JsonBox.dir/src/Value.cpp.o
    [ 27%] Building CXX object CMakeFiles/JsonBox.dir/src/SolidusEscaper.cpp.o
    [ 36%] Building CXX object CMakeFiles/JsonBox.dir/src/Escaper.cpp.o
    [ 45%] Building CXX object CMakeFiles/JsonBox.dir/src/Indenter.cpp.o
    [ 54%] Building CXX object CMakeFiles/JsonBox.dir/src/IndentCanceller.cpp.o
    [ 63%] Building CXX object CMakeFiles/JsonBox.dir/src/JsonParsingError.cpp.o
    [ 72%] Building CXX object CMakeFiles/JsonBox.dir/src/Convert.cpp.o
    [ 81%] Linking CXX static library libJsonBox.a
    [ 81%] Built target JsonBox
    Scanning dependencies of target example1
    [ 90%] Building CXX object CMakeFiles/example1.dir/examples/main.cpp.o
    [100%] Linking CXX executable example1
    [100%] Built target example1
    
    ~/.../test/build ⃲ ls 
    CMakeCache.txt       example1             libJsonBox.a
    CMakeFiles/          Export.h             Makefile
    cmake_install.cmake  JsonBoxConfig.cmake  
    
    ~/.../test/build ⃲ make install DESTDIR=.
    [ 81%] Built target JsonBox
    [100%] Built target example1
    Install the project...
    -- Install configuration: ""
    -- Installing: ./usr/local/lib/libJsonBox.a
    -- Installing: ./usr/local/include/JsonBox/Convert.h
    -- Installing: ./usr/local/include/JsonBox/Escaper.h
    -- Installing: ./usr/local/include/JsonBox/Grammar.h
    -- Installing: ./usr/local/include/JsonBox/IndentCanceller.h
    -- Installing: ./usr/local/include/JsonBox/Indenter.h
    -- Installing: ./usr/local/include/JsonBox/JsonParsingError.h
    -- Installing: ./usr/local/include/JsonBox/JsonWritingError.h
    -- Installing: ./usr/local/include/JsonBox/OutputFilter.h
    -- Installing: ./usr/local/include/JsonBox/SolidusEscaper.h
    -- Installing: ./usr/local/include/JsonBox/Value.h
    -- Installing: ./usr/local/include/JsonBox.h
    -- Installing: ./usr/local/include/JsonBox/Export.h
    -- Installing: ./usr/local/lib/cmake/JsonBoxConfig.cmake
    -- Installing: ./usr/local/lib/cmake/JsonBoxConfig-noconfig.cmake
    
    ~/.../test/build ⃲ 
    
You might want to set those cmake options instead if using DESTDIR:

    CMAKE_PREFIX_PATH
    CMAKE_INSTALL_PREFIX

See `cmake --help-variable <var>` for more informations about their use.

**Comment by mbabuskov** [comment]
I was always simply including the sources into my project and not building the library. Thanks.
