### ISSUE TITLE
Value::tryGetBoolean()  does not return defaultValue as documented

### ISSUE THREAD

**Issue by gwesterberg** [anhero/JsonBox#42]
The documentation indicates that Value::tryGetBoolean() _returns Value's boolean value, or defaultValue if the value doesn't contain a boolean_.  However, if the value doesn't contain a boolean it actually returns EMPTY_BOOL instead of returning defaultValue.

**Comment by madbranch** [comment]
Thank you for finding this bug, I have fixed it.
