### ISSUE TITLE
getDouble() fails if number has no decimal digits and no exponent

### ISSUE THREAD

**Issue by rhuitl** [anhero/JsonBox#9]
When writing double to a JSON file, some numbers are exported without decimal digits (which by itself is fine and shouldn't be changed):

                        "coeffs" : [
                                -4.14925e-05,
                                -3.12482e-05,
                                1,
                                -0.00257958
                        ],

However when loading this file, getDouble() returns the third element as 0.0 because it is treated as an integer. I think getDouble() should return integer values as doubles, because there is no loss involved in the conversion and the current behavior is broken.

**Comment by madbranch** [comment]
I am currently preparing for a new release soon.

**Comment by russell-taylor** [comment]
The sooner the better.  We just tripped over this on another project and are pulling that commit to avoid the problem.
